### ISSUE TITLE
Don't try to find collaborators when the user has no push access to a repository

### ISSUE THREAD

**Issue by saveriomiroddi** [saveriomiroddi/geet#121]
When a user has no push access to a repository, it's not possible to get the collaborators list, and it will raise an error:

    lib/geet/github/api_interface.rb:58:in `block in send_request': Must have push access to view repository collaborators. (RuntimeError)
    from lib/geet/github/api_interface.rb:51:in `loop'
    from lib/geet/github/api_interface.rb:51:in `send_request'
    from lib/geet/github/collaborator.rb:11:in `list'
    from lib/geet/git/repository.rb:123:in `attempt_provider_call'
    from lib/geet/git/repository.rb:36:in `collaborators'
    from lib/geet/utils/attributes_selection_manager.rb:58:in `block in find_attribute_entries'

This must be somewhat detected and prevented.

- [x] fix for issue creation
- [ ] fix for PR creation

**Comment by saveriomiroddi** [comment]
See https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level
