### ISSUE TITLE
Issue/PR creation fails when milestone+upstream is set

### ISSUE THREAD

**Issue by saveriomiroddi** [saveriomiroddi/geet#89]
Command: `geet {issue,pr} create -m- -u`

Stacktrace:

    Finding milestone...
    lib/geet/utils/manual_list_selection.rb:17:in `select': No milestone provided! (RuntimeError)
      from lib/geet/services/create_issue.rb:136:in `select_entries'
      from lib/geet/services/create_issue.rb:34:in `execute'
      from bin/geet:30:in `launch'

**Comment by saveriomiroddi** [comment]
Not an issue, but the service should tell that there are no milestones, rather than none has been chosen.
